config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :foods
  resources :events
  resources :restaurants
  resources :users

  root 'pages#home'
  get '/dashboard' => 'pages#dashboard'
  get '/users/:id' => 'users#show'

  # mailbox folder routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  # conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController
	before_action :authenticate_user!

  def inbox
    @inbox = mailbox.inbox
    @active = :inbox
  end

  def sent
    @sent = mailbox.sentbox
    @active = :sent
  end

  def trash
    @trash = mailbox.trash
    @active = :trash
  end


end

app/helpers/mailbox_helper.rb
module MailboxHelper

	def unread_messages_count
    # how to get the number of unread messages for the current user
    # using mailboxer
    mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end

end

app/views/mailbox/_folder_view.html.erb
<section>
<div class="container main-section">
<div class="row">
  <div class="col m12">
    <!-- we'll configure this to compose new conversations later -->
    <%= link_to "Compose", new_conversation_path, class: "btn waves-effect waves-light" %>
  </div>

  <div class="col m4">
        <%= render 'mailbox/folders' %>
  </div>

  <div class="col m8">
      <% if is_conversation %>
          <%= render 'conversations/form' %>
        <% else %>
          <%= render partial: 'conversations/conversation', collection: messages %>
        <% end %>
  </div>

</div>
</div>

</section>

app/views/mailbox/_folders.html.erb
<div class="collection">
    <%= link_to mailbox_inbox_path, method: "GET", class: "collection-item" do  %>
        Inbox
        <span class="new badge"><%=unread_messages_count%></span>
    <% end %>

    <%= link_to mailbox_sent_path, method: "GET", class: "collection-item" do %>
        Sent
    <% end %>   

    <%= link_to mailbox_trash_path, method: "GET", class: "collection-item" do %>
        Trash
    <% end %>  

  </div>

app/views/mailbox/inbox.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @inbox } %>

app/views/mailbox/sent.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @sent } %>

app/views/mailbox/trash.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @trash } %>