config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :foods
  resources :events
  resources :restaurants
  resources :users

  root 'pages#home'
  get '/dashboard' => 'pages#dashboard'
  get '/users/:id' => 'users#show'

  # mailbox folder routes
  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  # conversations
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant
  has_many :comments

  def guests 
  	guests = []
  	guest_lists = GuestList.where(event_id: self)
  	guest_lists.each do |guest_list|
  		guest = User.find(guest_list.user_id)
  		guests.push(guest)
  	end
  	guests
  end

  acts_as_commentable
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  def index
    @events = Event.all
  end

  # GET /events/1
  def show
    @new_comment    = Comment.build_from(@event, current_user.id, "")

    @restaurant = @event.restaurant
    @map_hash = Gmaps4rails.build_markers(@restaurant) do |restaurant, marker|
      marker.lat restaurant.latitude
      marker.lng restaurant.longitude
    end

    if params[:join] == "true"
      GuestList.create(:event_id => @event.id, :user_id => current_user.id)

      flash[:notice] = 'You succesfully joined an event.'
      redirect_to event_path(@event), "method"=>"get"
    end

  end

  # GET /events/new
  def new
    @event = Event.new
    @restaurant = Restaurant.find_by :yelp_id => params[:restaurant]
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @restaurant = Restaurant.find_by :yelp_id => params[:event][:restaurant]
    @event = Event.new(event_params)
    @event.user_id = current_user.id
    @event.user = current_user
    @event.restaurant_id = @restaurant.id
    @event.time = params[:event][:time]

    respond_to do |format|
      if @event.save
        format.html { redirect_to dashboard_url }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:user_id, :restaurant_id, :message)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="input-field col s12 m8 offset-m2">
      <h1>Host Event</h1>
    </div>
    <% if @restaurant.nil? %>
      <div class="input-field col s12 m8 offset-m2">
        <%= f.label :restaurant_id %><br>
        <%= f.text_field :restaurant_id %>  
      </div>
    <% else %>
     <div class="field col s12 m8 offset-m2">
        <label for="disabled">Restaurant</label>
        <input disabled value="<%= @restaurant.name %>" id="disabled" type="text" class="validate">
        <%= f.hidden_field :restaurant, :value => @restaurant.yelp_id %>
      </div>
    <% end %>
    
    <div class="input-field col s12 m8 offset-m2">
      <%= f.label :time %><br>
      <%= f.text_field :time, class: 'timepicker' %>  
      <script type="text/javascript">
        // $('.datepicker').pickadate({
        //   selectMonths: true, // Creates a dropdown to control month
        //   selectYears: 15 // Creates a dropdown of 15 years to control year
        // });
        $('.timepicker').pickatime();
      </script>
    </div>
    <div class="input-field col s12 m8 offset-m2">
      <%= f.label :message %><br>
      <%= f.text_area :message, class: 'materialize-textarea' %>
    </div>
    <div class="actions input-field col s12 m8 offset-m2">
      <%= f.submit 'Host Event', class:'btn waves-effect waves-light' %>
    </div>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Restaurant</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.user %></td>
        <td><%= event.restaurant %></td>
        <td><%= event.message %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<%= render 'form' %>

app/views/events/show.html.erb
<section>
	<div class="row">
		<div class="hide-on-med-and-down col l3"> <!-- Note that "m4 l3" was added -->
		<!-- Grey navigation panel
		This content will be:
		3-columns-wide on large screens,
		4-columns-wide on medium screens,
		12-columns-wide on small screens  -->
		<div class="card medium">
			<div class="card-image">
				<!-- <img class="activator" src="http://materializecss.com/images/office.jpg"> -->
				<img src="<%= (@event.restaurant.image_url).sub('/ms', '/348s') %>">
				<!-- <div class="card-title">3:00 pm</div> -->
			</div>
			<div class="card-content">
				<br>
				<div class="rating-image">
					<img src="<%= @event.restaurant.rating_img_url %>">
					<p class="rating-view"><%= @event.restaurant.review_count %> reviews</p>
				</div>
				
				<p>Meet @ <%= @event.time %></p>
				<p>Host: <%= link_to @event.user.firstname+ " " +@event.user.lastname, user_path(@event.user) if @event.user %></p>
				
				<div class="event-user">
					<div class="user-info">
					</div>
					<div class="join-link">
						<% if current_user != @event.user && GuestList.exists?(event_id: @event.id, user_id: current_user.id) == false %>
						<p>
							<%= link_to 'JOIN', event_path(@event, :join => "true"), :method => :get
							%>
						</p>
						<% end %>
					</div>
				</div>
			</div>
			<div class="card-reveal">
				<span class="card-title grey-text text-darken-4">
					<%= @event.restaurant.name %>
					<i class="material-icons right">close</i>
				</span>
				<p><%= @event.restaurant.address.html_safe %></p>
				<hr>
				<div class="row valign-wrapper">
					<div class="col s2">
						<img src="http://materializecss.com/images/yuna.jpg" alt="" class="circle responsive-img"> <!-- notice the "circle" class -->
					</div>
					<div class="col s10">
						<span class="black-text">
							<%= @event.message %>
						</span>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="col s12 m8 l9">
		<ul class="collapsible popout" data-collapsible="accordion">
			<li>
				<div class="collapsible-header active"><i class="material-icons">perm_identity</i>Who's Going</div>
				<div class="collapsible-body">
					<br>
					<div class="row">
						<div class="chip teal white-text">
							<img src="<%= @event.user.picture %>" alt="Contact Person">
							<%= link_to @event.user.firstname + " " + @event.user.lastname, user_path(@event.user), :class => 'white-text' %>
						</div>
						<% @event.guests.each do |guest| %>
						<div class="chip">
							<img src="<%= guest.picture %>" alt="Contact Person">
							<%= link_to guest.firstname + " " + guest.lastname, user_path(guest), :class => 'black-text' %>
						</div>
						<% end %>
					</div>
					<br>
				</div>
			</li>
			<li>
				<div class="collapsible-header" onclick="displayMap()"><i class="material-icons">place</i>Where</div>
				<div class="collapsible-body">
					<p><%= @event.restaurant.address.html_safe %></p>
				</div>
				<div class="map-container">
					<div id="map" class="map"></div>
				</div>
			</li>
			<li>
				<div class="collapsible-header"><i class="material-icons">comment</i>Comments</div>
				
				<div class="collapsible-body">
					
				</div>
				<%= render partial: "comments/template", locals: {commentable: @event, new_comment: @comment} %>
				</br>
			</li>
		</ul>
	</div>
</div>
</section>

<script type="text/javascript">
	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {scrollwheel: false}, internal: {id: 'map'}}, function(){
		markers = handler.addMarkers(<%=raw @map_hash.to_json %>);
		handler.bounds.extendWith(markers);
		handler.fitMapToBounds();
		handler.getMap().setZoom(15);
	});
</script>